# Generated by Django 6.0.1 on 2026-01-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarifyingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('text', 'Free Text'), ('scale', 'Scale (1-10)')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for choice questions')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='profiles.clarifyingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Main subject to learn', max_length=200)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('goals', models.TextField(blank=True, help_text='Learning goals and objectives')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Learning preferences as JSON')),
                ('weekly_hours', models.PositiveIntegerField(default=5, help_text='Hours available per week')),
                ('deadline', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('language', models.CharField(default='en', help_text='Preferred language code', max_length=10)),
                ('age_range', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_plus', '55+')], max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner Profile',
                'verbose_name_plural': 'Learner Profiles',
            },
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='learner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifying_questions', to='profiles.learnerprofile'),
        ),
    ]
