# Generated by Django 6.0.1 on 2026-01-15 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgerianCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, help_text='Arabic name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('company_type', models.CharField(choices=[('startup', 'Startup / شركة ناشئة'), ('sme', 'SME / مؤسسة صغيرة ومتوسطة'), ('enterprise', 'Large Enterprise / شركة كبيرة'), ('government', 'Government / حكومي'), ('multinational', 'Multinational / متعددة الجنسيات'), ('freelance', 'Freelance Platform / منصة عمل حر')], default='sme', max_length=20)),
                ('industry', models.CharField(choices=[('tech', 'Technology / تكنولوجيا'), ('finance', 'Finance & Banking / بنوك ومالية'), ('telecom', 'Telecommunications / اتصالات'), ('energy', 'Energy & Oil / طاقة وبترول'), ('ecommerce', 'E-commerce / تجارة إلكترونية'), ('education', 'Education / تعليم'), ('health', 'Healthcare / صحة'), ('services', 'Services / خدمات'), ('manufacturing', 'Manufacturing / صناعة')], default='tech', max_length=20)),
                ('wilaya', models.CharField(default='alger', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('required_skills', models.JSONField(default=list, help_text='Skills this company typically needs')),
                ('is_hiring', models.BooleanField(default=True)),
                ('remote_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Algerian Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('skill_name_ar', models.CharField(blank=True, max_length=100)),
                ('demand_score', models.FloatField(default=0.5, help_text='Overall demand 0-1')),
                ('growth_trend', models.CharField(choices=[('rising', 'Rising / في ارتفاع'), ('stable', 'Stable / مستقر'), ('declining', 'Declining / في انخفاض')], default='stable', max_length=20)),
                ('related_skills', models.JSONField(default=list, help_text='Related skills')),
                ('average_salary', models.CharField(blank=True, help_text='Average salary in DZD', max_length=100)),
                ('job_count', models.PositiveIntegerField(default=0, help_text='Number of active jobs requiring this skill')),
                ('category', models.CharField(blank=True, help_text='Skill category', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Demands',
                'ordering': ['-demand_score'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured answer data'),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='category',
            field=models.CharField(choices=[('background', 'Background / الخلفية'), ('goals', 'Goals / الأهداف'), ('preferences', 'Preferences / التفضيلات'), ('availability', 'Availability / التوفر'), ('job_market', 'Job Market / سوق العمل')], default='background', max_length=20),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Must answer to proceed'),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='question_text_ar',
            field=models.TextField(blank=True, help_text='Arabic version'),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='question_text_en',
            field=models.TextField(blank=True, help_text='English version'),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='question_text_fr',
            field=models.TextField(blank=True, help_text='French version'),
        ),
        migrations.AddField(
            model_name='clarifyingquestion',
            name='target_field',
            field=models.CharField(blank=True, help_text='Profile field to update with answer', max_length=50),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School / ابتدائي'), ('middle', 'Middle School / متوسط'), ('secondary', 'Secondary School / ثانوي'), ('bac', 'Baccalauréat / باكالوريا'), ('licence', 'Licence (L1-L3)'), ('master', 'Master (M1-M2)'), ('doctorate', 'Doctorate / دكتوراه'), ('self_taught', 'Self-taught / تعلم ذاتي')], help_text='Education level', max_length=20),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='is_employed',
            field=models.BooleanField(default=False, help_text='Currently employed'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Currently a student'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='questions_answered',
            field=models.BooleanField(default=False, help_text='Has answered initial questions'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='seeking_job',
            field=models.BooleanField(default=True, help_text='Looking for job opportunities'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('alger', 'Alger'), ('oran', 'Oran'), ('constantine', 'Constantine'), ('annaba', 'Annaba'), ('setif', 'Sétif'), ('blida', 'Blida'), ('batna', 'Batna'), ('djelfa', 'Djelfa'), ('tlemcen', 'Tlemcen'), ('bejaia', 'Béjaïa'), ('tizi_ouzou', 'Tizi Ouzou'), ('ouargla', 'Ouargla'), ('other', 'Other / أخرى')], help_text='Region in Algeria', max_length=50),
        ),
        migrations.AlterField(
            model_name='clarifyingquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Options for choice questions (multilingual)'),
        ),
        migrations.AlterField(
            model_name='clarifyingquestion',
            name='question_text',
            field=models.TextField(help_text="Question in user's preferred language"),
        ),
        migrations.AlterField(
            model_name='clarifyingquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('text', 'Free Text'), ('scale', 'Scale (1-10)'), ('yes_no', 'Yes/No')], default='single_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18 / أقل من 18'), ('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_plus', '55+ / +55')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية (Arabic)'), ('fr', 'Français (French)'), ('en', 'English'), ('ar_dz', 'الدارجة الجزائرية (Algerian Dialect)')], default='ar', help_text='Preferred language', max_length=10),
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time / دوام كامل'), ('part_time', 'Part-time / دوام جزئي'), ('contract', 'Contract / عقد'), ('internship', 'Internship / تدريب'), ('freelance', 'Freelance / عمل حر')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level / مبتدئ'), ('junior', 'Junior (1-2 years) / جونيور'), ('mid', 'Mid-level (3-5 years) / متوسط'), ('senior', 'Senior (5+ years) / سينيور')], default='entry', max_length=20)),
                ('required_skills', models.JSONField(default=list, help_text='Required skills for this job')),
                ('nice_to_have_skills', models.JSONField(default=list, help_text='Nice to have skills')),
                ('wilaya', models.CharField(default='alger', max_length=50)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_range', models.CharField(blank=True, help_text="e.g., '80,000 - 120,000 DZD'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('application_url', models.URLField(blank=True)),
                ('demand_score', models.FloatField(default=0.5, help_text='Market demand score 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_opportunities', to='profiles.algeriancompany')),
            ],
            options={
                'verbose_name_plural': 'Job Opportunities',
                'ordering': ['-demand_score', '-created_at'],
            },
        ),
    ]
