# Generated by Django 6.0.1 on 2026-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_algeriancompany_skilldemand_answer_answer_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clarifyingquestion',
            name='target_field',
            field=models.CharField(blank=True, help_text='Profile field to update with answer', max_length=50, null=True),
        ),
    ]
