# Generated by Django 6.0.1 on 2026-01-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('total_estimated_hours', models.FloatField(default=0)),
                ('completed_hours', models.FloatField(default=0)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('model_versions', models.JSONField(blank=True, default=dict, help_text='LLM and embedding model versions used')),
                ('input_profile_hash', models.CharField(blank=True, help_text='Hash of input profile for reproducibility', max_length=64)),
                ('is_pinned', models.BooleanField(default=False, help_text='User pinned this roadmap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='profiles.learnerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(blank=True, default=list, help_text='Learning objectives for this step')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Order in the roadmap')),
                ('estimated_hours', models.FloatField(default=1.0)),
                ('actual_hours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='locked', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text="User pinned this step (won't regenerate)")),
                ('user_notes', models.TextField(blank=True)),
                ('mastery_check_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='roadmaps.roadmapstep')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('roadmap', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='StepResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='User pinned this resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_usages', to='resources.resource')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_resources', to='roadmaps.roadmapstep')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('step', 'resource')},
            },
        ),
    ]
