# Generated by Django 6.0.1 on 2026-01-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('generate_roadmap', 'Generate Roadmap'), ('regenerate_roadmap', 'Regenerate Roadmap'), ('fetch_resources', 'Fetch Resources'), ('generate_questions', 'Generate Questions')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Job',
                'verbose_name_plural': 'AI Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
