# Generated by Django 6.0.1 on 2026-01-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('course', 'Course'), ('book', 'Book'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('exercise', 'Exercise')], default='article', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='e.g., YouTube, Coursera, Medium', max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time in minutes', null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of topic tags')),
                ('quality_score', models.FloatField(default=0.5, help_text='Quality score 0-1')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-quality_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_working', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resources.resource')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
