# Generated by Django 6.0.1 on 2026-01-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='algeria_relevant',
            field=models.BooleanField(default=True, help_text='Relevant for Algerian job market'),
        ),
        migrations.AddField(
            model_name='resource',
            name='channel_name',
            field=models.CharField(blank=True, help_text='YouTube channel name', max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Arabic description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='has_subtitles',
            field=models.BooleanField(default=False, help_text='Has Arabic/French subtitles'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_arabic_friendly',
            field=models.BooleanField(default=False, help_text='Good for Arabic speakers'),
        ),
        migrations.AddField(
            model_name='resource',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages for books', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resource',
            name='skills_covered',
            field=models.JSONField(blank=True, default=list, help_text='Skills taught by this resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Arabic title', max_length=300),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of videos in playlist', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='YouTube views or similar'),
        ),
        migrations.AddField(
            model_name='resource',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='YouTube channel ID', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, help_text='YouTube playlist ID', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner / مبتدئ'), ('intermediate', 'Intermediate / متوسط'), ('advanced', 'Advanced / متقدم')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية (Arabic)'), ('ar_dz', 'الدارجة الجزائرية (Algerian)'), ('fr', 'Français (French)'), ('en', 'English'), ('multi', 'Multilingual / متعدد اللغات')], default='ar', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video / فيديو'), ('youtube_tutorial', 'YouTube Tutorial / درس يوتيوب'), ('youtube_playlist', 'YouTube Playlist / قائمة تشغيل'), ('youtube_channel', 'YouTube Channel / قناة يوتيوب'), ('article', 'Article / مقال'), ('course', 'Course / دورة'), ('book', 'Book / كتاب'), ('ebook', 'E-Book / كتاب إلكتروني'), ('pdf', 'PDF Document / مستند PDF'), ('tutorial', 'Tutorial / درس'), ('documentation', 'Documentation / توثيق'), ('exercise', 'Exercise / تمرين'), ('project', 'Project / مشروع'), ('github_repo', 'GitHub Repository')], default='article', max_length=20),
        ),
    ]
